name: update readme

on: 
  schedule:
    - cron: '0 8 * * *'
  push:
    branches:
     - main
  issues:
    types: [pinned]
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: junxnone/update-readme@tmdkg
        with:
          push_branch: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          actor: ${{ github.actor }}
